#!/bin/bash

function main() {

	#process arguements
	args="-L 6006:bdi:6006 -L 6007:bdi:6007 -L 6000:bdi:22"
	if [ "$1" != "local" ]
	then
		args="-J gate ${args}"
	fi
	
	#conect
	ssh bdi $args
	#sshfs -o uid=1011,allow_other,default_permissions,IdentityFile=/home/john/.ssh/id_ecdsa john@localhost:6000/ /home/john/mnt/bdi

}

main $1

