#!/bin/bash

function main() {

	#process arguements
	args="-L 6006:bdi:6006 -L 6007:bdi:6007 -L 6000:bdi:22"
	if [ "$1" != "local" ]
	then
		args="-J gate ${args}"
	fi
	
	#conect
	ssh bdi $args

}

main $1

