#!/bin/bash

if [ $# -eq 0 ]
then
    printf "usage: binbackup [push/pull]\n"
    exit 1
fi
if [ $1 == 'push' ]
then
    rsync -av --delete /home/john/bin/ /home/john/Dropbox/bin/
elif [ $1 == 'pull' ]
then
    rsync -av --delete /home/john/Dropbox/bin/ /home/john/bin/
fi
exit 0
