#!/bin/bash

function main() {
	hosts=("bdi" "nlp")
	if [[ "${hosts[*]}" =~ "$1" ]]; then 
		host=$1
	else
		echo "invalid host"
		exit 0
	fi

	#process arguements
	args="-L 6006:bdi:6006 -L 6007:bdi:6007 -L 6000:bdi:22 -L 6008:bdi:8888"
	if [ "$2" != "local" ]
	then
		args="-J gate ${args}"
	fi
	
	#connect
	ssh $host $args
}

main $@

