#!/bin/bash

function main() {
    hosts=("bdi" "nlp" "gpu2")
    if [[ "${hosts[*]}" =~ "$1" ]]; then 
        host=$1
    else
        echo "invalid host"
        exit 0
    fi

    #port forwarding arguments
    args="-L 6006:${host}:6006 \
        -L 6007:${host}:6007 \
        -L 6000:${host}:22 \
        -L 6008:${host}:6008 \
        -L 8888:${host}:8888 \
        -L 8889:${host}:8889"
    
    #connect
    ssh $host $args
}

main $@


