#!/usr/bin/env python
import argparse
import datasets
import pandas as pd
import IPython
import numpy as np
from pprint import pprint
from datasets import Dataset

def main(args):
    datasets.disable_caching()
    ds_path = args.data_path
    ext = ds_path.split('.')[-1]
    
    if ext == 'xlsx':
        ds = pd.read_excel(ds_path)
        ds = Dataset.from_pandas(ds)
    else:
        ds = datasets.load_dataset(
            ext,
            data_files=ds_path
        )

        if list(ds.keys()) == ['train']:
            ds = ds['train']

    IPython.embed()

if __name__ == '__main__':
    argparser = argparse.ArgumentParser()
    argparser.add_argument(
        'data_path',
        help='the path of the dataset to load',
    )
    args = argparser.parse_args()

    main(args)
