#!/bin/bash

function install_openvpn(){
	cd ${HOME}
	mkdir .tmp
	cd .tmp

	sudo apt install apt-transport-https -y
	wget https://swupdate.openvpn.net/repos/openvpn-repo-pkg-key.pub
	sudo apt-key add openvpn-repo-pkg-key.pub
	sudo wget -O /etc/apt/sources.list.d/openvpn3.list https://swupdate.openvpn.net/community/openvpn3/repos/openvpn3-$1.list
	sudo apt update && sudo apt install openvpn3

	cd ${HOME}
	rm -rf ${HOME}/.tmp
}

install_openvpn $@
