#!/bin/bash


function mitaku() {

    lsout=$(ls | grep .rar)
    readarray -t archives <<< "$lsout"

    if [[ "$1" == "-d" ]]; then
        echo "${#archives[@]} command(s) to run:"
        echo
    fi

    for arc in "${archives[@]}"; do
        if [[ "$arc" == "" ]]; then
            continue
        elif [[ "$1" == "-d" ]]; then
            echo unrar x -p'mitaku.net' "$arc"
        else
            if unrar x -p'mitaku.net' "$arc"; then
                rm "$arc"
            fi
        fi
    done
}

mitaku $@
