#!/bin/bash

# use the following if you get a mounting error
# fusermount -u $mountpoint
function main(){
	# mount nas drives
	if [ "$1" == "" ]; then
		sshfs -o uid=1000,default_permissions,IdentityFile=${HOME}/.ssh/id_ecdsa truenas:/mnt/pool1/h/ ${HOME}/mnt/.h
		sshfs -o uid=1000,default_permissions,IdentityFile=${HOME}/.ssh/id_ecdsa synology:media/ ${HOME}/mnt/media
	# mount bdi and nlp servers
	elif [ "$1" == "bdi" ] || [ "$1" == "nlp" ]; then
		sshfs -o uid=1000,default_permissions,IdentityFile=${HOME}/.ssh/id_ecdsa2 ${1}:/data/john/ ${HOME}/mnt/${1}
	else
		echo "invalid host"
	fi
}

main $@
