#!/bin/bash

# use the following if you get a mounting error
# fusermount -u $mountpoint
function main(){

    base_dir=${HOME}/mnt

	# mount nas drives
	if [ "$1" == "" ]; then
        # create directories if they don't exist
        mkdir -p ${base_dir}/.h
        mkdir -p ${base_dir}/media

        # mount
		sshfs -o reconnect truenas:/mnt/pool1/h/ ${base_dir}/.h
		sshfs -o reconnect synology:media/ ${base_dir}/media
	# mount external servers
    elif [ "$1" == "bdi_shared" ] || [ "$1" == "nlp_shared" ]; then
        srvr=$(cut -c 1-3 <<< $1)
        trgt=${base_dir}/${1}
        mkdir -p ${trgt}

        sshfs ${srvr}:/data/shared ${trgt}
	elif [ "$1" == "bdi" ] || [ "$1" == "nlp" ]; then
        trgt=${base_dir}/${1}
        mkdir -p ${trgt}
		sshfs ${1}:/data/john/ ${trgt}
    elif [ "$1" == "gpu1" ] || [ "$1" == "gpu2" ]; then
        trgt=${base_dir}/${1}
        mkdir -p ${trgt}
		sshfs ${1}: ${trgt}
	else
		echo "invalid host"
	fi
}

main $@
