#!/bin/bash

function main(){
    nc bdi.cse.eng.auburn.edu 22 -w 1 &> /dev/null
    result=$?

    if [ "$1" == "-v" ]; then
        if [ $result == 1 ]; then
            echo "this computer is outside auburn"
        else
            echo "this computer is inside auburn"
        fi
    fi

    # 1 means that we are outside the auburn network so we should return 0
    # 0 means we are inside so we should return 1
    if [ $result == 0 ]; then
        return 1
    else
        return 0
    fi
}

main $@

