#!/bin/bash

function main(){
    nc bdi.cse.eng.auburn.edu 22 -w 1 &> /dev/null
    result=$?

    if [ "$1" == "-v" ]; then
        if [ $result == 1 ]; then
            echo "this computer is outside auburn"
        else
            echo "this computer is inside auburn"
        fi
    fi

    return $result
}

main $@

