#!/bin/bash
if [ "$1" = "-p" ]
then
	rsync -av "synology:/volume1/h/.p/" "/run/media/john/ssd1/"
fi

rsync -av --delete "/home/john/.local/share/mcomix/" "/run/media/john/ssd1/.bm/"
rsync -av --delete "/run/media/john/ssd1/" "10.123.95.171:/volume1/h/"
