#!/bin/bash
if [ "$1" = "-p" ]
then
	rsync -av "10.123.95.171:/volume1/h/.p/" "/run/media/john/ssd1/"
fi

rsync -av --delete --update "/home/john/.local/share/mcomix/" "10.123.95.171:/volume1/h/.bm/"

rsync -av --delete "10.123.95.171:/volume1/h/" "/run/media/john/ssd1/"
rsync -av --delete "10.123.95.171:/volume1/h/" "/media/john/ssd1/"
