#!/bin/bash

function main() {

    # set default branch name
    git config --global init.defaultBranch main
	
	# set username
	git config --global user.email jmsalvador2395@gmail.com
	git config --global user.name john

	# setting vimdiff for editing and mergetool
	git config --global core.editor vim
	git config merge.tool vimdiff
	git config merge.conflictstyle diff3
	git config mergetool.prompt false
}

main $@
