#!/bin/bash

source helper_functions

function pull_git_repos() {
	config_dir="configs"
	cd
	mkdir ${config_dir}
	cd ${config_dir}

	repos=("linux_vimrc")

	for i in "${repos[@]}"; do
		mkdir $i
		cd $i
		git init
		git pull git@github.com:jmsalvador2395/${i}.git
		echo "finished pulling git repository"
		cd ..
	done
}

function create_directories() {
	base_dir=${HOME}/mnt/
	create_dir ${base_dir}/media
	create_dir ${base_dir}/.h
	create_dir ${base_dir}/bdi
}

function main() {
	working_dir=$(pwd)
	pull_git_repos
	create_directories
	cd ${working_dir}

	#create temporary download directory
	mkdir .tmp
	cd .tmp

	sudo apt update && sudo apt upgrade -y

	#install brave browser (for mint)
	sudo apt install apt-transport-https curl
	sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
	echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list
	sudo apt update
	sudo apt install brave-browser -y

	#install anaconda
	sudo apt install \
		libgl1-mesa-glx \
		libegl1-mesa \
		libxrandr2 \
		libxrandr2 \
		libxss1 \
		libxcursor1 \
		libxcomposite1 \
		libasound2 \
		libxi6 \
		libxtst6 \
		-y
	
	#may have to change this later
	wget https://repo.anaconda.com/archive/Anaconda3-2022.05-Linux-x86_64.sh

	sh *.sh -b -p ${HOME}/anaconda3
	#rm *.sh
	cd ${working_dir}

	#install signal
	wget -O- https://updates.signal.org/desktop/apt/keys.asc | gpg --dearmor > signal-desktop-keyring.gpg
	cat signal-desktop-keyring.gpg | sudo tee -a /usr/share/keyrings/signal-desktop-keyring.gpg > /dev/null

	echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main' | \
		sudo tee -a /etc/apt/sources.list.d/signal-xenial.list
	
	sudo apt update && sudo apt install signal-desktop -y


	#general installs
	sudo apt install \
		tmux \
		sshfs \
		mcomix \
		steam \
		spotify-client \
		mpv \
		-y
			
	#rm -Rf .tmp
}

main $@
