#!/bin/bash

function main() {
	if [ "$1" == "jupyter" ]; then
		jupyter-notebook --ip=0.0.0.0 --no-browser &
	elif [ "$1" == "tensorboard" ]; then
        if [ "$3" == "" ]; then
            port=6006
        else
            port="$3"
        fi
		tensorboard \
            --logdir="$2" \
            --port="${port}" \
            --bind_all \
            --load_fast=false \
            --reload_multifile=true \
            &
	fi
}

main $@
