#!/bin/bash

function main() {
	if [ "$1" == "jupyter" ]; then
		jupyter-notebook --ip=0.0.0.0 --no-browser
	elif [ "$1" == "tensorboard" ]; then
		tensorboard --logdir="$2" --bind_all --load_fast=false
	fi
}

main $@
