#!/usr/bin/env python

import re
import os
import argparse

def strip_scanners(args):
	pattern = r'^\[.*\]'

	cwd = os.getcwd()
	files = os.listdir(cwd)
	for fname in files:
		new_name = re.sub(pattern, '', fname).strip()
		tokens = new_name.split()
		if 'Vol.' in tokens:
			tokens[1] = f'{int(tokens[1]):0{args["vol_zeros"]}d}'
		else:
			continue
		tail = tokens.pop(-1)
		num, ext = tail[:-4], tail[-4:]
		try:
			num = f'{int(num):0{args["chapter_zeros"]}d}'
		except:
			num = f'{float(num):0{args["chapter_zeros"]+2}.1f}'
		new_name = ' '.join(tokens) + f' {num}{ext}'
		if args['commit']:
			os.rename(f'{cwd}/{fname}', f'{cwd}/{new_name}')
		print(f'old name: {fname}\nnew name: {new_name}\n')
	
	if not args['commit']:
		print('\n** Changes not commited. run with -c to commit **\n')
	else:
		print('\n** Changes Commited **\n')

if __name__ == '__main__':
	parser = argparse.ArgumentParser()
	parser.add_argument(
		'vol_zeros',
		type=int,
		choices=[1, 2, 3, 4],
	)
	parser.add_argument(
		'chapter_zeros',
		type=int,
		choices=[1, 2, 3, 4],
	)
	parser.add_argument(
		'-c',
		'--commit',
		default=False,
		action='store_true',
	)
	args = vars(parser.parse_args())
	strip_scanners(args)
