#!/bin/bash

function main() {
	if [ "$1" == "" ]; then
		umount /home/john/mnt/.h
		umount /home/john/mnt/media
	elif [ "$1" == "bdi" ]; then
		umount /home/john/mnt/bdi
	elif [ "$1" == "nlp" ]; then
		umount /home/john/mnt/nlp
	fi
}

main $1
