#!/bin/bash

function main(){
    if [ -d "/media/john/backup" ]; then
        rsync -av --delete --info=progress2 /home/john/.local/share/mcomix/ truenas:/mnt/pool1/h/.bm/
        rsync -av --delete --info=progress2 truenas:/mnt/pool1/h/ /media/john/backup/h/
    else
        echo "Backup Failed: /media/john/backup not mounted"
    fi
}

main $@
